### ISSUE TITLE
$(...).fullCalendar is not a function 

### ISSUE THREAD

**Issue by diquispe** [maddhatter/laravel-fullcalendar#151]
Console Error

$(...).fullCalendar is not a function

Laravel 5.8.*

Not Showing Calendar (With error) with Fulcalendar 4.3.0
Working with Fullcalendar 3.9.0

 "maddhatter/laravel-fullcalendar": "^1.3"

NOTE:Is this package really abandoned??, what better or more updated alternative is there?

**Comment by LeonardoCostaSabino** [comment]
https://github.com/agjmills/laravel-fullcalendar, he forked this package and update for new versions  Laravel >=5.8
